name = "BoundaryValueProblems"
uuid = "4e0c136c-7fd7-450f-8fba-42b64cbda8b5"
authors = ["Vedant Puri <vedantpuri@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
